export interface Product {
  id: string;
  name: string;
  category: string;
  image: string;
  currentStock: number;
  requiredStock: number;
  status: 'ok' | 'attention' | 'risk';
  trend: 'up' | 'down' | 'stable';
  demandTrend: number[];
  riskBadge?: 'stockout' | 'overstock' | 'expiry';
  price?: number;
  turnoverRate?: number;
}

export interface Alert {
  id: string;
  productId: string;
  severity: 'critical' | 'warning' | 'info';
  message: string;
  timestamp: Date;
  type: string;
  storeId?: string;
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  timestamp: Date;
  read: boolean;
  type: 'alert' | 'info' | 'success' | 'warning';
  storeId?: string;
}

export interface InventoryPreferences {
  lowStockThreshold: number;
  autoReorderEnabled: boolean;
  autoReorderThreshold: number;
  autoReorderQuantity: number;
  productPriority: 'fast-moving' | 'seasonal' | 'premium' | 'all';
  preferredSupplier: string;
  deliveryFrequency: 'daily' | 'weekly' | 'bi-weekly' | 'monthly';
  overstockProtection: boolean;
  maxStockLimit: number;
  categoryRules: {
    fruits: { enabled: boolean; threshold: number; maxStock: number };
    frozen: { enabled: boolean; threshold: number; maxStock: number };
    snacks: { enabled: boolean; threshold: number; maxStock: number };
    dairy: { enabled: boolean; threshold: number; maxStock: number };
    produce: { enabled: boolean; threshold: number; maxStock: number };
    bakery: { enabled: boolean; threshold: number; maxStock: number };
  };
}

export interface Store {
  id: string;
  name: string;
  city: string;
  region: string;
  status: 'online' | 'offline';
  salesTarget: number;
  actualSales: number;
  forecastAccuracy: number;
  stockoutRate: number;
  overstockRate: number;
  averageStock: number;
  topProduct: string;
  staffCount: number;
  lastUpdated: Date;
  managerName: string;
  managerPhone: string;
  inventoryPreferences?: InventoryPreferences;
}

// Default inventory preferences for all stores
const defaultInventoryPreferences: InventoryPreferences = {
  lowStockThreshold: 10,
  autoReorderEnabled: true,
  autoReorderThreshold: 20,
  autoReorderQuantity: 50,
  productPriority: 'fast-moving',
  preferredSupplier: 'FreshMart Central Supply',
  deliveryFrequency: 'weekly',
  overstockProtection: true,
  maxStockLimit: 500,
  categoryRules: {
    fruits: { enabled: true, threshold: 15, maxStock: 200 },
    frozen: { enabled: true, threshold: 25, maxStock: 300 },
    snacks: { enabled: true, threshold: 30, maxStock: 400 },
    dairy: { enabled: true, threshold: 12, maxStock: 250 },
    produce: { enabled: true, threshold: 18, maxStock: 350 },
    bakery: { enabled: true, threshold: 20, maxStock: 180 },
  },
};

// 25 Indian Cities - FreshMart Stores
export const mockStores: Store[] = [
  {
    id: 'store-1',
    name: 'FreshMart Hyderabad Central',
    city: 'Hyderabad',
    region: 'South',
    status: 'online',
    salesTarget: 58000,
    actualSales: 62500,
    forecastAccuracy: 95.2,
    stockoutRate: 0.8,
    overstockRate: 1.2,
    averageStock: 89,
    topProduct: 'Organic Milk',
    staffCount: 32,
    lastUpdated: new Date(),
    managerName: 'Rajesh Kumar',
    managerPhone: '+91-9876543210',
    inventoryPreferences: { ...defaultInventoryPreferences },
  },
  {
    id: 'store-2',
    name: 'FreshMart Bengaluru Premium',
    city: 'Bengaluru',
    region: 'South',
    status: 'online',
    salesTarget: 65000,
    actualSales: 68900,
    forecastAccuracy: 93.8,
    stockoutRate: 1.2,
    overstockRate: 1.8,
    averageStock: 87,
    topProduct: 'Fresh Tomatoes',
    staffCount: 35,
    lastUpdated: new Date(),
    managerName: 'Priya Sharma',
    managerPhone: '+91-9876543211',
  },
  {
    id: 'store-3',
    name: 'FreshMart Chennai Marina',
    city: 'Chennai',
    region: 'South',
    status: 'online',
    salesTarget: 52000,
    actualSales: 54300,
    forecastAccuracy: 92.1,
    stockoutRate: 1.5,
    overstockRate: 2.1,
    averageStock: 85,
    topProduct: 'Bananas',
    staffCount: 28,
    lastUpdated: new Date(),
    managerName: 'Vikram Singh',
    managerPhone: '+91-9876543212',
  },
  {
    id: 'store-4',
    name: 'FreshMart Pune Downtown',
    city: 'Pune',
    region: 'West',
    status: 'online',
    salesTarget: 48000,
    actualSales: 51200,
    forecastAccuracy: 94.5,
    stockoutRate: 0.9,
    overstockRate: 1.4,
    averageStock: 88,
    topProduct: 'Carrots',
    staffCount: 26,
    lastUpdated: new Date(),
    managerName: 'Anjali Patel',
    managerPhone: '+91-9876543213',
  },
  {
    id: 'store-5',
    name: 'FreshMart Delhi Central',
    city: 'Delhi',
    region: 'North',
    status: 'online',
    salesTarget: 72000,
    actualSales: 75800,
    forecastAccuracy: 96.2,
    stockoutRate: 0.6,
    overstockRate: 1.1,
    averageStock: 91,
    topProduct: 'Spinach',
    staffCount: 38,
    lastUpdated: new Date(),
    managerName: 'Arun Kumar',
    managerPhone: '+91-9876543214',
  },
  {
    id: 'store-6',
    name: 'FreshMart Mumbai Gateway',
    city: 'Mumbai',
    region: 'West',
    status: 'online',
    salesTarget: 78000,
    actualSales: 81500,
    forecastAccuracy: 95.8,
    stockoutRate: 0.7,
    overstockRate: 1.3,
    averageStock: 90,
    topProduct: 'Apples',
    staffCount: 42,
    lastUpdated: new Date(),
    managerName: 'Neha Desai',
    managerPhone: '+91-9876543215',
  },
  {
    id: 'store-7',
    name: 'FreshMart Kolkata Heritage',
    city: 'Kolkata',
    region: 'East',
    status: 'online',
    salesTarget: 44000,
    actualSales: 46800,
    forecastAccuracy: 91.2,
    stockoutRate: 1.8,
    overstockRate: 2.3,
    averageStock: 82,
    topProduct: 'Potatoes',
    staffCount: 24,
    lastUpdated: new Date(),
    managerName: 'Suraj Mukherjee',
    managerPhone: '+91-9876543216',
  },
  {
    id: 'store-8',
    name: 'FreshMart Ahmedabad Market',
    city: 'Ahmedabad',
    region: 'West',
    status: 'online',
    salesTarget: 46000,
    actualSales: 49200,
    forecastAccuracy: 93.4,
    stockoutRate: 1.3,
    overstockRate: 1.7,
    averageStock: 86,
    topProduct: 'Onions',
    staffCount: 25,
    lastUpdated: new Date(),
    managerName: 'Rohan Joshi',
    managerPhone: '+91-9876543217',
  },
  {
    id: 'store-9',
    name: 'FreshMart Jaipur Palace',
    city: 'Jaipur',
    region: 'North',
    status: 'online',
    salesTarget: 42000,
    actualSales: 45600,
    forecastAccuracy: 92.8,
    stockoutRate: 1.4,
    overstockRate: 1.9,
    averageStock: 84,
    topProduct: 'Cabbages',
    staffCount: 22,
    lastUpdated: new Date(),
    managerName: 'Deepak Singh',
    managerPhone: '+91-9876543218',
  },
  {
    id: 'store-10',
    name: 'FreshMart Indore Central',
    city: 'Indore',
    region: 'Central',
    status: 'online',
    salesTarget: 38000,
    actualSales: 40200,
    forecastAccuracy: 90.5,
    stockoutRate: 2.1,
    overstockRate: 2.5,
    averageStock: 80,
    topProduct: 'Lettuce',
    staffCount: 20,
    lastUpdated: new Date(),
    managerName: 'Meera Chand',
    managerPhone: '+91-9876543219',
  },
  {
    id: 'store-11',
    name: 'FreshMart Bhopal Market',
    city: 'Bhopal',
    region: 'Central',
    status: 'online',
    salesTarget: 40000,
    actualSales: 42800,
    forecastAccuracy: 91.7,
    stockoutRate: 1.6,
    overstockRate: 2.2,
    averageStock: 83,
    topProduct: 'Cucumbers',
    staffCount: 21,
    lastUpdated: new Date(),
    managerName: 'Sanjay Verma',
    managerPhone: '+91-9876543220',
  },
  {
    id: 'store-12',
    name: 'FreshMart Visakhapatnam Beach',
    city: 'Visakhapatnam',
    region: 'South',
    status: 'online',
    salesTarget: 39000,
    actualSales: 41500,
    forecastAccuracy: 89.8,
    stockoutRate: 2.3,
    overstockRate: 2.8,
    averageStock: 78,
    topProduct: 'Broccoli',
    staffCount: 19,
    lastUpdated: new Date(),
    managerName: 'Ravi Chandra',
    managerPhone: '+91-9876543221',
  },
  {
    id: 'store-13',
    name: 'FreshMart Goa Trade Center',
    city: 'Gurgaon',
    region: 'North',
    status: 'online',
    salesTarget: 54000,
    actualSales: 57900,
    forecastAccuracy: 94.3,
    stockoutRate: 1.0,
    overstockRate: 1.5,
    averageStock: 87,
    topProduct: 'Peppers',
    staffCount: 29,
    lastUpdated: new Date(),
    managerName: 'Harsh Patel',
    managerPhone: '+91-9876543222',
  },
  {
    id: 'store-14',
    name: 'FreshMart Faridabad Express',
    city: 'Faridabad',
    region: 'North',
    status: 'online',
    salesTarget: 36000,
    actualSales: 38400,
    forecastAccuracy: 91.4,
    stockoutRate: 1.7,
    overstockRate: 2.1,
    averageStock: 81,
    topProduct: 'Beans',
    staffCount: 18,
    lastUpdated: new Date(),
    managerName: 'Rakesh Singh',
    managerPhone: '+91-9876543223',
  },
  {
    id: 'store-15',
    name: 'FreshMart Ghaziabad Smart',
    city: 'Ghaziabad',
    region: 'North',
    status: 'online',
    salesTarget: 37000,
    actualSales: 39600,
    forecastAccuracy: 90.9,
    stockoutRate: 1.9,
    overstockRate: 2.4,
    averageStock: 79,
    topProduct: 'Peas',
    staffCount: 19,
    lastUpdated: new Date(),
    managerName: 'Neelam Sharma',
    managerPhone: '+91-9876543224',
  },
  {
    id: 'store-16',
    name: 'FreshMart Lucknow Heritage',
    city: 'Lucknow',
    region: 'North',
    status: 'online',
    salesTarget: 41000,
    actualSales: 43900,
    forecastAccuracy: 92.6,
    stockoutRate: 1.4,
    overstockRate: 1.8,
    averageStock: 84,
    topProduct: 'Radishes',
    staffCount: 22,
    lastUpdated: new Date(),
    managerName: 'Bhavna Singh',
    managerPhone: '+91-9876543225',
  },
  {
    id: 'store-17',
    name: 'FreshMart Kanpur Market',
    city: 'Kanpur',
    region: 'North',
    status: 'online',
    salesTarget: 35000,
    actualSales: 37200,
    forecastAccuracy: 90.2,
    stockoutRate: 2.0,
    overstockRate: 2.6,
    averageStock: 77,
    topProduct: 'Garlic',
    staffCount: 17,
    lastUpdated: new Date(),
    managerName: 'Kiran Kumar',
    managerPhone: '+91-9876543226',
  },
  {
    id: 'store-18',
    name: 'FreshMart Patna Central',
    city: 'Patna',
    region: 'East',
    status: 'online',
    salesTarget: 32000,
    actualSales: 34100,
    forecastAccuracy: 89.1,
    stockoutRate: 2.4,
    overstockRate: 3.0,
    averageStock: 75,
    topProduct: 'Ginger',
    staffCount: 16,
    lastUpdated: new Date(),
    managerName: 'Manoj Singh',
    managerPhone: '+91-9876543227',
  },
  {
    id: 'store-19',
    name: 'FreshMart Noida Express',
    city: 'Noida',
    region: 'North',
    status: 'online',
    salesTarget: 50000,
    actualSales: 53400,
    forecastAccuracy: 93.9,
    stockoutRate: 1.1,
    overstockRate: 1.6,
    averageStock: 86,
    topProduct: 'Coriander',
    staffCount: 27,
    lastUpdated: new Date(),
    managerName: 'Divya Verma',
    managerPhone: '+91-9876543228',
  },
  {
    id: 'store-20',
    name: 'FreshMart Coimbatore Garden',
    city: 'Coimbatore',
    region: 'South',
    status: 'online',
    salesTarget: 43000,
    actualSales: 45800,
    forecastAccuracy: 92.3,
    stockoutRate: 1.5,
    overstockRate: 2.0,
    averageStock: 83,
    topProduct: 'Mint',
    staffCount: 23,
    lastUpdated: new Date(),
    managerName: 'Anitha Nair',
    managerPhone: '+91-9876543229',
  },
  {
    id: 'store-21',
    name: 'FreshMart Madurai Temple',
    city: 'Madurai',
    region: 'South',
    status: 'online',
    salesTarget: 39000,
    actualSales: 41200,
    forecastAccuracy: 91.0,
    stockoutRate: 1.8,
    overstockRate: 2.3,
    averageStock: 81,
    topProduct: 'Fenugreek',
    staffCount: 20,
    lastUpdated: new Date(),
    managerName: 'Selvam Kumar',
    managerPhone: '+91-9876543230',
  },
  {
    id: 'store-22',
    name: 'FreshMart Trichy Express',
    city: 'Tiruchirappalli',
    region: 'South',
    status: 'online',
    salesTarget: 37000,
    actualSales: 39500,
    forecastAccuracy: 90.6,
    stockoutRate: 1.9,
    overstockRate: 2.4,
    averageStock: 80,
    topProduct: 'Turmeric',
    staffCount: 19,
    lastUpdated: new Date(),
    managerName: 'Ramesh Kumar',
    managerPhone: '+91-9876543231',
  },
  {
    id: 'store-23',
    name: 'FreshMart Vijayawada Market',
    city: 'Vijayawada',
    region: 'South',
    status: 'online',
    salesTarget: 41000,
    actualSales: 43600,
    forecastAccuracy: 91.8,
    stockoutRate: 1.6,
    overstockRate: 2.1,
    averageStock: 82,
    topProduct: 'Chillies',
    staffCount: 21,
    lastUpdated: new Date(),
    managerName: 'Krishna Rao',
    managerPhone: '+91-9876543232',
  },
  {
    id: 'store-24',
    name: 'FreshMart Guntur Heritage',
    city: 'Guntur',
    region: 'South',
    status: 'online',
    salesTarget: 38000,
    actualSales: 40200,
    forecastAccuracy: 90.4,
    stockoutRate: 2.0,
    overstockRate: 2.5,
    averageStock: 79,
    topProduct: 'Methi',
    staffCount: 19,
    lastUpdated: new Date(),
    managerName: 'Suresh Kumar',
    managerPhone: '+91-9876543233',
  },
  {
    id: 'store-25',
    name: 'FreshMart Warangal Central',
    city: 'Warangal',
    region: 'South',
    status: 'online',
    salesTarget: 36000,
    actualSales: 38100,
    forecastAccuracy: 89.7,
    stockoutRate: 2.2,
    overstockRate: 2.7,
    averageStock: 77,
    topProduct: 'Basil',
    staffCount: 18,
    lastUpdated: new Date(),
    managerName: 'Devendra Singh',
    managerPhone: '+91-9876543234',
  },
];
export const productImages = {
  // Dairy
  'dairy-milk': '/products/dairy-milk.png',
  'dairy-yogurt': '/products/yogurt.png',
  'dairy-cheese': '/products/cheese.png',
  'dairy-butter': '/products/butter.png',

  // Produce
  'produce-tomatoes': '/products/tomatoes.png',
  'produce-bananas': '/products/bananas.png',
  'produce-carrots': '/products/carrots.png',
  'produce-spinach': '/products/spinach.png',
  'produce-apples': '/products/apples.png',
  'produce-onions': '/products/onions.png',
  'produce-potatoes': '/products/potatoes.png',

  // Bakery
  'bakery-bread': '/products/bread.png',
  'bakery-croissant': '/products/croissant.png',
  'bakery-muffins': '/products/muffins.png',

  // Pantry
  'pantry-oil': '/products/oil.png',
  'pantry-rice': '/products/rice.png',
  'pantry-pasta': '/products/pasta.png',
  
  // Legacy product IDs (keeping for backward compatibility)
  'prod-1': 'https://images.unsplash.com/photo-1550583724-b2692b25a968?w=400&h=400&fit=crop',
  'prod-2': 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=400&fit=crop',
  'prod-3': 'https://images.unsplash.com/photo-1599599810990-b70ce0f6a046?w=400&h=400&fit=crop',
  'prod-4': 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=400&fit=crop',
  'prod-5': 'https://images.unsplash.com/photo-1599020814156-8e559a2df924?w=400&h=400&fit=crop',
  'prod-6': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=400&fit=crop',
  'prod-7': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=400&fit=crop',
  'prod-8': 'https://images.unsplash.com/photo-1599020814464-aab41d1bee64?w=400&h=400&fit=crop',
  'prod-9': 'https://images.unsplash.com/photo-1585518419759-3f4faf9f2c20?w=400&h=400&fit=crop',
  'prod-10': 'https://images.unsplash.com/photo-1599599810104-f0a89db0dfda?w=400&h=400&fit=crop',
  'prod-11': 'https://images.unsplash.com/photo-1599020814733-8d1b3f0fd04d?w=400&h=400&fit=crop',
  'prod-12': 'https://images.unsplash.com/photo-1599020814872-8f1266f2f12b?w=400&h=400&fit=crop',
  'prod-13': 'https://images.unsplash.com/photo-1585535320615-ba7c45ff9ff1?w=400&h=400&fit=crop',
  'prod-14': 'https://images.unsplash.com/photo-1585518419759-3f4faf9f2c20?w=400&h=400&fit=crop',
  'prod-15': 'https://images.unsplash.com/photo-1599020814733-8d1b3f0fd04d?w=400&h=400&fit=crop',
};

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Organic Whole Milk - 1L',
    category: 'Dairy',
    image: productImages['dairy-milk'],
    currentStock: 245,
    requiredStock: 300,
    status: 'attention',
    trend: 'down',
    demandTrend: [280, 295, 312, 301, 289, 267, 245],
    price: 4.99,
    turnoverRate: 12.3,
  },
  {
    id: '2',
    name: 'Greek Yogurt - 500ml',
    category: 'Dairy',
    image: productImages['dairy-yogurt'],
    currentStock: 210,
    requiredStock: 280,
    status: 'attention',
    trend: 'down',
    demandTrend: [275, 265, 250, 235, 225, 215, 210],
    price: 3.99,
    turnoverRate: 11.2,
  },
  {
    id: '3',
    name: 'Organic Cheddar Cheese - 500g',
    category: 'Dairy',
    image: productImages['dairy-cheese'],
    currentStock: 85,
    requiredStock: 150,
    status: 'risk',
    trend: 'down',
    demandTrend: [145, 140, 132, 122, 112, 98, 85],
    price: 6.99,
    turnoverRate: 7.3,
    riskBadge: 'stockout',
  },
  {
    id: '4',
    name: 'Salted Butter - 500g',
    category: 'Dairy',
    image: productImages['dairy-butter'],
    currentStock: 160,
    requiredStock: 200,
    status: 'ok',
    trend: 'stable',
    demandTrend: [190, 185, 178, 170, 168, 165, 160],
    price: 3.49,
    turnoverRate: 9.1,
  },

  {
    id: '5',
    name: 'Fresh Tomatoes - 1kg',
    category: 'Produce',
    image: productImages['produce-tomatoes'],
    currentStock: 180,
    requiredStock: 250,
    status: 'attention',
    trend: 'down',
    demandTrend: [210, 235, 250, 245, 220, 195, 180],
    price: 2.49,
    turnoverRate: 9.8,
  },
  {
    id: '6',
    name: 'Ripe Bananas - 1 Bunch',
    category: 'Produce',
    image: productImages['produce-bananas'],
    currentStock: 320,
    requiredStock: 350,
    status: 'ok',
    trend: 'stable',
    demandTrend: [340, 345, 348, 350, 348, 342, 320],
    price: 1.99,
    turnoverRate: 14.2,
  },
  {
    id: '7',
    name: 'Organic Carrots - 500g',
    category: 'Produce',
    image: productImages['produce-carrots'],
    currentStock: 150,
    requiredStock: 200,
    status: 'risk',
    trend: 'down',
    demandTrend: [198, 189, 175, 162, 156, 150, 145],
    price: 1.79,
    turnoverRate: 8.5,
    riskBadge: 'stockout',
  },
  {
    id: '8',
    name: 'Fresh Spinach - 250g',
    category: 'Produce',
    image: productImages['produce-spinach'],
    currentStock: 120,
    requiredStock: 180,
    status: 'risk',
    trend: 'down',
    demandTrend: [175, 168, 155, 145, 132, 125, 120],
    price: 2.29,
    turnoverRate: 10.1,
  },
  {
    id: '9',
    name: 'Fresh Apples - 1kg',
    category: 'Produce',
    image: productImages['produce-apples'],
    currentStock: 260,
    requiredStock: 320,
    status: 'attention',
    trend: 'down',
    demandTrend: [310, 305, 298, 285, 275, 268, 260],
    price: 3.49,
    turnoverRate: 11.8,
  },
  {
    id: '10',
    name: 'Fresh Onions - 1kg',
    category: 'Produce',
    image: productImages['produce-onions'],
    currentStock: 280,
    requiredStock: 340,
    status: 'ok',
    trend: 'stable',
    demandTrend: [310, 315, 318, 320, 310, 295, 280],
    price: 2.10,
    turnoverRate: 10.5,
  },
  {
    id: '11',
    name: 'Fresh Potatoes - 2kg',
    category: 'Produce',
    image: productImages['produce-potatoes'],
    currentStock: 300,
    requiredStock: 350,
    status: 'ok',
    trend: 'stable',
    demandTrend: [330, 335, 340, 345, 335, 320, 300],
    price: 3.99,
    turnoverRate: 12.0,
  },

  {
    id: '12',
    name: 'Whole Wheat Bread',
    category: 'Bakery',
    image: productImages['bakery-bread'],
    currentStock: 280,
    requiredStock: 300,
    status: 'ok',
    trend: 'stable',
    demandTrend: [295, 298, 300, 302, 298, 290, 280],
    price: 2.99,
    turnoverRate: 13.5,
  },
  {
    id: '13',
    name: 'Butter Croissant',
    category: 'Bakery',
    image: productImages['bakery-croissant'],
    currentStock: 140,
    requiredStock: 200,
    status: 'attention',
    trend: 'down',
    demandTrend: [195, 185, 172, 160, 150, 145, 140],
    price: 3.29,
    turnoverRate: 9.3,
  },
  {
    id: '14',
    name: 'Blueberry Muffins (Pack of 4)',
    category: 'Bakery',
    image: productImages['bakery-muffins'],
    currentStock: 165,
    requiredStock: 220,
    status: 'ok',
    trend: 'stable',
    demandTrend: [200, 205, 210, 215, 205, 185, 165],
    price: 4.59,
    turnoverRate: 8.9,
  },

  {
    id: '15',
    name: 'Extra Virgin Olive Oil - 500ml',
    category: 'Pantry',
    image: productImages['pantry-oil'],
    currentStock: 95,
    requiredStock: 120,
    status: 'risk',
    trend: 'down',
    demandTrend: [118, 115, 108, 102, 98, 96, 95],
    price: 8.99,
    turnoverRate: 5.2,
  },
  {
    id: '16',
    name: 'Basmati Rice - 5kg',
    category: 'Pantry',
    image: productImages['pantry-rice'],
    currentStock: 180,
    requiredStock: 240,
    status: 'attention',
    trend: 'down',
    demandTrend: [230, 220, 210, 200, 195, 190, 180],
    price: 12.49,
    turnoverRate: 6.7,
  },
  {
    id: '17',
    name: 'Pasta - 1kg',
    category: 'Pantry',
    image: productImages['pantry-pasta'],
    currentStock: 210,
    requiredStock: 260,
    status: 'ok',
    trend: 'stable',
    demandTrend: [240, 245, 248, 250, 245, 230, 210],
    price: 4.99,
    turnoverRate: 7.8,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    productId: '4',
    severity: 'critical',
    message: 'Organic Carrots - Low Stock Alert',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    type: 'stockout',
  },
  {
    id: 'alert-2',
    productId: '7',
    severity: 'critical',
    message: 'Extra Virgin Olive Oil - Stockout Risk',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    type: 'stockout',
  },
  {
    id: 'alert-3',
    productId: '8',
    severity: 'warning',
    message: 'Spinach Bundle - Low Stock Level',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    type: 'inventory',
  },
  {
    id: 'alert-4',
    productId: '1',
    severity: 'warning',
    message: 'Organic Milk - Demand Increase Detected',
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    type: 'demand',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'High Demand Alert',
    message: 'Organic Milk demand increased 15% this week across all stores',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    read: false,
    type: 'alert',
  },
  {
    id: 'notif-2',
    title: 'Stock Replenishment',
    message: 'Fresh Tomatoes shipment arriving in 2 hours at Delhi store',
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    read: false,
    type: 'info',
  },
  {
    id: 'notif-3',
    title: 'Promotion Scheduled',
    message: 'Weekend special on Bananas - 20% discount approved',
    timestamp: new Date(Date.now() - 120 * 60 * 1000),
    read: true,
    type: 'success',
  },
  {
    id: 'notif-4',
    title: 'Temperature Alert',
    message: 'Refrigeration unit maintenance needed at Bengaluru store',
    timestamp: new Date(Date.now() - 240 * 60 * 1000),
    read: true,
    type: 'warning',
  },
];

export const categoryHeatmap = [
  { day: 'Monday', dairy: 85, produce: 72, bakery: 78, pantry: 68 },
  { day: 'Tuesday', dairy: 88, produce: 75, bakery: 82, pantry: 70 },
  { day: 'Wednesday', dairy: 92, produce: 80, bakery: 88, pantry: 75 },
  { day: 'Thursday', dairy: 90, produce: 78, bakery: 85, pantry: 73 },
  { day: 'Friday', dairy: 95, produce: 85, bakery: 92, pantry: 80 },
  { day: 'Saturday', dairy: 98, produce: 92, bakery: 96, pantry: 88 },
  { day: 'Sunday', dairy: 88, produce: 85, bakery: 90, pantry: 75 },
];

export const demandDrivers = [
  {
    name: 'Base Demand',
    impact: 60,
    description: 'Regular customer purchases and recurring demand',
  },
  {
    name: 'Weekend Boost',
    impact: 25,
    description: 'Higher shopping frequency on weekends',
  },
  {
    name: 'Seasonal Effects',
    impact: 10,
    description: 'Seasonal variations and weather impacts',
  },
  {
    name: 'Promotional Impact',
    impact: 5,
    description: 'Sales and promotional campaigns',
  },
];



export const stockRecommendations = {
  'prod-1': { recommended: 250, action: 'Increase', reason: 'High demand during weekends', additionalStock: 50 },
  'prod-2': { recommended: 180, action: 'Maintain', reason: 'Stable daily consumption', additionalStock: 0 },
  'prod-3': { recommended: 150, action: 'Increase', reason: 'Festival season approaching', additionalStock: 40 },
  'prod-4': { recommended: 200, action: 'Maintain', reason: 'Consistent performance', additionalStock: 0 },
  'prod-5': { recommended: 120, action: 'Reduce', reason: 'Low turnover rate', additionalStock: -30 },
  'prod-6': { recommended: 220, action: 'Increase', reason: 'Peak season demand', additionalStock: 60 },
  'prod-7': { recommended: 160, action: 'Maintain', reason: 'Seasonal stability', additionalStock: 0 },
  'prod-8': { recommended: 140, action: 'Reduce', reason: 'Overstock detected', additionalStock: -20 },
  'prod-9': { recommended: 190, action: 'Increase', reason: 'Growing customer preference', additionalStock: 45 },
  'prod-10': { recommended: 210, action: 'Maintain', reason: 'Optimal inventory level', additionalStock: 0 },
  'prod-11': { recommended: 170, action: 'Increase', reason: 'Weekend demand surge', additionalStock: 35 },
  'prod-12': { recommended: 130, action: 'Reduce', reason: 'Low sales velocity', additionalStock: -25 },
  'prod-13': { recommended: 240, action: 'Increase', reason: 'High customer preference', additionalStock: 55 },
  'prod-14': { recommended: 150, action: 'Maintain', reason: 'Stable consumption pattern', additionalStock: 0 },
  'prod-15': { recommended: 185, action: 'Increase', reason: 'Growing demand trend', additionalStock: 40 },
};

export const crossSellProducts = {
  'prod-1': ['prod-2', 'prod-4'],
  'prod-2': ['prod-1', 'prod-5'],
  'prod-3': ['prod-4', 'prod-6'],
  'prod-4': ['prod-1', 'prod-3'],
  'prod-5': ['prod-2', 'prod-7'],
  'prod-6': ['prod-3', 'prod-8'],
  'prod-7': ['prod-5', 'prod-9'],
  'prod-8': ['prod-6', 'prod-10'],
  'prod-9': ['prod-7', 'prod-11'],
  'prod-10': ['prod-8', 'prod-12'],
  'prod-11': ['prod-9', 'prod-13'],
  'prod-12': ['prod-10', 'prod-14'],
  'prod-13': ['prod-11', 'prod-15'],
  'prod-14': ['prod-12', 'prod-1'],
  'prod-15': ['prod-13', 'prod-2'],
};
